[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ff = "0.5"
ark-ec = "0.5"
ark-poly = "0.5"
ark-poly-commit = "0.5"
ark-std = "0.5"
ark-bls12-381 = "0.5" 

rand = "0.9.1"

