[package]
name = "ponk-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ff = "0.4"
ark-ec = "0.4"
ark-poly = "0.4"
ark-poly-commit = "0.4"
ark-std = "0.4"
ark-bls12-381 = "0.4" 
rand = "0.8"

